version: "3"

services:
  app:
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 80"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:80"
    profiles:
      - dev
      - production

  app-test:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      test-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - TESTING=1
      - POSTGRES_HOST=test-db
    ports:
      - "8000:80"
    profiles:
      - test

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.db
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - dev

  test-db:
    image: postgres:16-alpine
    env_file:
      - .env.db
    ports:
      - "5432:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - test

volumes:
  postgres_data:
