version: "3"

services:
  db:
    image: postgres:13.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.db

volumes:
  postgres_data:
