"""initial

Revision ID: 504fc01e4d11
Revises: 
Create Date: 2023-12-02 01:52:53.434720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '504fc01e4d11'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('auth_id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('auth_id')
                    )
    op.create_table('games',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('config', sa.JSON(), nullable=True),
                    sa.Column('game_started_time', sa.DateTime(), nullable=False),
                    sa.Column('game_ended_time', sa.DateTime(), nullable=True),
                    sa.Column('winner_id', sa.Integer(), nullable=True),
                    sa.Column('history', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['winner_id'], ['users.auth_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('wallets',
                    sa.Column('address', sa.String(length=64), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.auth_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('address')
                    )
    op.create_table('users_to_games',
                    sa.Column('users', sa.Integer(), nullable=True),
                    sa.Column('games', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['games'], ['games.id'], name='fk_games', ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['users'], ['users.auth_id'], name='fk_users', ondelete='CASCADE')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_to_games')
    op.drop_table('wallets')
    op.drop_table('games')
    op.drop_table('users')
    # ### end Alembic commands ###
